### ISSUE TITLE
Bug: Durable queue group doesn't receive next message after ACK

### ISSUE THREAD

**Issue by Alirun** [nats-io/stan.js#112]
I'm having a problem with durable queue group.

I receive messages one by one by setting `inFlightMax` to `1`.

If I publish messages one by one it works fine as expected, but when I publish two messages at the same time and first one is aknowleged really fast (within 500ms), the second message I receive only after `AckWait` timeout. And all others messages are being delayed by `AckWait` as well after that. Is this issue somehow related to `stan` or `nats-streaming-server` itself?

```
this._stan = require('node-nats-streaming').connect(config.natsStreaming.clusterId, 
this._clientId, {
        servers: config.nats.servers,
        json: true
      })
var opts = this._stan
          .subscriptionOptions()
          .setManualAckMode(true)
          .setAckWait(this._ackWait)
          .setDeliverAllAvailable()
          .setDurableName(this._durable)
          .setMaxInFlight(this._maxInFlight)
var subscription = this._stan.subscribe(this._channel, this._queueGroup, opts)
        subscription.on('message', this._callback)
```
The most important values are
`this._maxInFlight == 1`
`this._ackWait == 30 * 1000`

**Comment by aricart** [comment]
@alirun One question, do you have another queue subscriber that is not ack'ing which is intercepting one of the messages and only when that message fails the ack timeout, it is sent to the client that is working?

**Comment by aricart** [comment]
I made a publisher and subscriber that you can use and follow this example.
https://gist.github.com/aricart/c2b85e0f9fbda69993194e5cbea8643b

Hope it helps.

**Comment by Rochet2** [comment]
We are having a similar problem. The queue should be processed one by one, but sometimes the messages just stop flowing in after a message is completed.

In one of our cases a single subscriber (subscribed alone) stopped receiving messages completely, even if the ack wait is set to 1 minute. It did not recover even after restarting everything.
There were more messages being generated every second, but the subscriber never got any of them and no errors were produced that we could see.

here is our producer (publisher), at the top you can see the messages. Every message is acked once only.
https://github.com/UniversityOfHelsinkiCS/oodikone/blob/be2456ce3fe5a8cd19e349ac06b985a3730753b0/services/backend/updater_writer/index.js#L36

Here is our consumer (subscriber):
https://github.com/UniversityOfHelsinkiCS/oodikone/blob/be2456ce3fe5a8cd19e349ac06b985a3730753b0/services/updater_scheduler/index.js#L89-L138

There is only one consumer and multiple producers.

**Comment by Alirun** [comment]
@Rochet2 We are still having an issue as well

If we publish two messages in a row with one subscriber it only receives first one and only after "ack wait" receives second one.

It's out of our priorities for now, that's why I can't provide more info for an issue at the moment and make some tests. But we will definitely get to it in few weeks.
