### ISSUE TITLE
Add a callback to subscription.close()

### ISSUE THREAD

**Issue by KoryNunn** [nats-io/stan.js#123]
* EDIT: I initially didn't see that there was a 'closed' event, but I think it'd still be good to implement this.

Currently `subscription.close()` runs asynchronous operations when called, ~but there is no way to know that it is complete before exiting node~.

This is currently a bigger issue than it should be because nats-streaming-server has a bug where messages sent to a consumer that is killed immediately will not be sent after `AckWait` but instead much later (N seconds)

Suggestions:

 - Add a callback:  `subscription.close(callback)`
 - Return a promise: `await subscription.close()`
 - ~Emit a close event: `subscription.close(); subscription.on('closed', ...)`~

My current solution is:

```js
subscription.close()
subscription.on('closed', exitNode)
```

I'm actually a little suspicious that `subscription.close()` doesn't work as expected, since I seem to still receive messages seconds after calling it.

**Comment by aricart** [comment]
@KoryNunn the `close` handler for the subscription is emitted in response to the server response to calling close. So effectively is exactly what you are asking for. Let me verify on my side that after calling close, and the close event is emitted, that no additional messages are seen by the client.

**Comment by aricart** [comment]
@KoryNunn verified that after the subscription's `close` event is sent no additional messages are delivered to the subscription. Note that indeed, if you call `close`, it is possible for additional messages to be delivered until the callback is invoked. If you need to throttle messages more closely, you may consider doing manual acks and setting the max number of messages that can be inflight for the subscrition (`setMaxInFlight`).
