### ISSUE TITLE
Unable to limit messages to one at a time

### ISSUE THREAD

**Issue by Rochet2** [nats-io/stan.js#129]
We try to have nats streaming post messages one by one to multiple subscribers.
The subscribers are running in docker containers and there are 3 instances or more of the same subscriber.

When a message starts processing, the message ID is printed along with 'starting'. When the message finishes processing the message ID is printed along with the time it took to process.

Even if we have set max in flight setting to 1, sometimes nats streaming pushes multiple messages for the service to handle.
For example below I have highlighted that 3 messages came in and started processing before any of them ended.

<details>

```diff
updater_writer_1     | 2019-07-25T16:17:51.170898884Z starting 014716173
updater_writer_5     | 2019-07-25T16:17:51.751942881Z 014720619: 2759.244ms
updater_writer_5     | 2019-07-25T16:17:51.759055944Z starting 014621310
updater_writer_2     | 2019-07-25T16:17:53.662452619Z 013038768: 5429.205ms
updater_writer_2     | 2019-07-25T16:17:53.683829290Z starting 014446508
updater_writer_1     | 2019-07-25T16:17:54.248946275Z 014716173: 3077.951ms
updater_writer_1     | 2019-07-25T16:17:54.261619296Z starting 014722507
updater_writer_5     | 2019-07-25T16:17:54.665748494Z 014621310: 2906.523ms
updater_writer_5     | 2019-07-25T16:17:54.669985571Z starting 013826682
updater_writer_4     | 2019-07-25T16:17:55.823961485Z 014455230: 5654.933ms
updater_writer_4     | 2019-07-25T16:17:55.831152448Z starting 014718472
updater_writer_5     | 2019-07-25T16:17:56.103210499Z 013826682: 1433.070ms
updater_writer_5     | 2019-07-25T16:17:56.109676179Z starting 014809080
updater_writer_1     | 2019-07-25T16:17:56.886240323Z 014722507: 2624.328ms
updater_writer_1     | 2019-07-25T16:17:56.894728099Z starting 014997756
updater_writer_4     | 2019-07-25T16:17:57.258740978Z 014718472: 1427.465ms
updater_writer_4     | 2019-07-25T16:17:57.265194773Z starting 014721964
updater_writer_3     | 2019-07-25T16:17:57.440137803Z 014987818: 6578.258ms
updater_writer_3     | 2019-07-25T16:17:57.444456899Z starting 014923403
updater_writer_1     | 2019-07-25T16:17:57.675485566Z 014997756: 780.618ms
updater_writer_1     | 2019-07-25T16:17:57.681701340Z starting 011026248
updater_writer_2     | 2019-07-25T16:17:58.389189111Z 014446508: 4705.370ms
updater_writer_2     | 2019-07-25T16:17:58.396959460Z starting 014324086
updater_writer_4     | 2019-07-25T16:17:59.283489502Z 014721964: 2018.014ms
updater_writer_4     | 2019-07-25T16:17:59.326178684Z starting 013128458
updater_writer_3     | 2019-07-25T16:17:59.488178331Z 014923403: 2043.548ms
updater_writer_3     | 2019-07-25T16:17:59.490909640Z starting 014708343
updater_writer_2     | 2019-07-25T16:18:00.163523552Z starting 014710425
updater_writer_1     | 2019-07-25T16:18:00.196739808Z starting 011038919
updater_writer_5     | 2019-07-25T16:18:00.224312566Z starting 014470752
updater_writer_1     | 2019-07-25T16:18:00.244667890Z starting 010941421
updater_writer_2     | 2019-07-25T16:18:00.266255542Z starting 014588291
updater_writer_3     | 2019-07-25T16:18:00.272301347Z starting 014340691
- updater_writer_5     | 2019-07-25T16:18:00.276430111Z starting 014696662
- updater_writer_5     | 2019-07-25T16:18:00.287629560Z starting 014486872
- updater_writer_5     | 2019-07-25T16:18:00.288668697Z starting 014939060
updater_writer_1     | 2019-07-25T16:18:00.292477235Z starting 014325742
updater_writer_3     | 2019-07-25T16:18:00.292686289Z starting 014141641
updater_writer_4     | 2019-07-25T16:18:00.321387054Z starting 014146808
updater_writer_3     | 2019-07-25T16:18:00.330356554Z starting 014937279
updater_writer_1     | 2019-07-25T16:18:00.340923774Z starting 013741563
updater_writer_2     | 2019-07-25T16:18:00.344757253Z starting 014809831
updater_writer_2     | 2019-07-25T16:18:00.350632324Z starting 014020542
updater_writer_4     | 2019-07-25T16:18:00.353727242Z starting 014484285
updater_writer_4     | 2019-07-25T16:18:00.354160830Z starting 014406069
updater_writer_3     | 2019-07-25T16:18:00.374879699Z starting 013763143
updater_writer_5     | 2019-07-25T16:18:00.539845992Z 014809080: 4430.012ms
updater_writer_5     | 2019-07-25T16:18:00.541159725Z starting 014049138
updater_writer_3     | 2019-07-25T16:18:00.569543196Z 014708343: 1078.459ms
updater_writer_3     | 2019-07-25T16:18:00.580133346Z starting 014333682
updater_writer_4     | 2019-07-25T16:18:00.849986630Z starting 014458130
updater_writer_2     | 2019-07-25T16:18:01.574222600Z 014324086: 3176.702ms
updater_writer_2     | 2019-07-25T16:18:01.577577421Z starting 014055274
updater_writer_1     | 2019-07-25T16:18:01.692750946Z 011026248: 4010.600ms
updater_writer_1     | 2019-07-25T16:18:01.696824259Z starting 010967544
```

</details>

Since pretty much every container did the same thing at pretty much the same time, I would assume this has something to do with ack wait time being triggered.
The services have likely been restarted once or twice before this behavior occurred, so it is possible that some messages never acked.

you can see our subscriber here: https://github.com/UniversityOfHelsinkiCS/oodikone/blob/be2456ce3fe5a8cd19e349ac06b985a3730753b0/services/backend/updater_writer/index.js#L27-L46
The subscribers take messages that were created multiple hours beforehand.

**Comment by KoryNunn** [comment]
I've come across this as well, and apparently it's by-design.

From here: https://github.com/nats-io/stan.go/issues/214#issuecomment-445110575

"This is the idea behind MaxInflight: server does not send new messages until the number of outstanding acks fall below that threshold. Note that messages don't have to be acknowledged in order.

With queue subs, though, the nice thing is that the MaxInflight is per-member, meaning that if you start a new queue sub, it would be able to receive new messages until its own maxInflight is reached."

I would personally love to see that be an option, since it is not obvious or intuitive given the documentation around maxInFlight

**Comment by aricart** [comment]
The functionality that you are looking for is really a worker queue. You can simulate it with a durable subscription, manualAckMode, ackWait, and maxInFlight subscription options, but as @KoryNunn explained, if you have a queue subscribers, the server will send a message to each of the clients. If one of the clients exceeds it's ackWait, or the ack message is sent, the message will be resent to a client. That is why nats-streaming has "At Least Once" semantics.
Likely you'll want at the very least to make your messages are idempotent.
