### ISSUE TITLE
Publish error value is an empty object

### ISSUE THREAD

**Issue by AaronFriel** [nats-io/stan.js#130]
Occasionally the stan.js client enters into an unusual state, which I have had significant difficulty diagnosing, and I see messages published with `err = {}` and `aGuid` will be a valid NUID.

The code in question I have is this:

```
    connection.publish(
      subject,
      JSON.stringify(envelope),
      (err: unknown, ...args: unknown[]) => {
        if (err) {
          reject({ err, args });
        } else {
          resolve();
        }
      },
    );
```

And if err is defined, then I see a log message like this:

```
  err: {
   args: [
    "A0BALR97NCQ3HHS9T4S38V"     
   ],
   err: {}
  }
```

Unfortunately it seems this error occurs even when the message _did successfully publish_, so when our system retries the publish, it creates duplicate messages. It turns our delivery into "at least N times" delivery.

I have two questions:

1. How is the error an empty object? I can't find anywhere in `stan.js` that an empty object would be passed here. Is this a protobuf deserialization failure?

2. Is the empty object indicative of success in this case? Can I safely check if the object is an empty object and assume that the publish was successful?

Edit:

I've confirmed that these publishes are succeeding in every case we see the error value `{}`. This spurious error causes us to republish, which causes many messages to be duplicated. Using a tracing framework, we tag each message as it moves between services with a consistent trace ID. In an ideal case, we would see for a given trace ID log messages like this:

Service 1: `publishing to subject A`
Service 2: `message received from subject A`
Service 2: `publishing to subject B`
Service 3: `message received from subject B`
...

We are instead seeing:

Service 1: `publishing to subject A`
Service 1: `error "{}" publishing to subject A in $TIMEOUT seconds`
Service 2: `message received from subject A`
Service 1: `retrying publishing to subject A`
Service 1: `error "{}" publishing to subject A`
Service 2: `message received from subject A`
Service 2: `publishing to subject B`
Service 2: `error "{}" publishing to subject B in $TIMEOUT seconds`
Service 2: `retrying publish to subject B`
Service 3: `message received from subject B`
...

And so on. Basically, each publish is being retried multiple times, succeeding each time and returning with an error code, causing a cascade of infinitely duplicated messages.

**Comment by kozlovic** [comment]
Do you see any error in the server log? If you are running the server with `-SDV` do you see messages being acknowledged by the server back to publisher?

I am not too familiar with the Node client, but if the publish is asynchronous (like we have in other libraries), the call would invoke a callback with the result of the publish, which should contain the GUID - that you could correlate with server log - and the error if any.
So it almost sounds like you are getting proper behavior, but then I would think that your application would never have worked (that is, would have always "retry" the publish). I will let @aricart comment on the API.

**Comment by AaronFriel** [comment]
Hey @kozlovic 

We were only logging with `-SD` so I don't see the STAN protocol messages. I do see however a lot of messages like this:

```
[1] 2019/08/02 17:49:50.604584 [DBG] STREAM: [Client:dispatcher-5f8d6d47b8-q98bw-3abbc9496fc5] Removed member from durable queue subscription ...
```

Around the time errors began. In fact, I see mostly those kind of errors for the next 10-15 minutes.

Re: async API: The publish is asynchronous, and we wrap the publish in a promise that rejects if the error is truthy (an object, an array, a non-empty string, true, ...).

**Comment by kozlovic** [comment]
These are not error per-se. They are debug messages to indicate that a durable queue member left the group (either subscription closed, or connection of the subscription closed).

**Comment by aricart** [comment]
@AaronFriel a couple of observations - The ackhandler in typescript is defined as (Error | undefined).  I do see on line #515 that it is possible for the error argument to be a string. However, I don't see where you could get an empty object - the field in the protobuf for an error is a string.

Also I don't see in the context of the snippet you have any references to a Promise, so not sure about the resolve/reject calls. If I do an example that publishes messages, the output in my case is always the same:

```
let stan = require('node-nats-streaming').connect('test-cluster', 'test');

stan.on('connect', function () {
    for(let i=0; i < 1000; i++) {
        stan.publish('foo', JSON.stringify({counter: i}), function (err, guid) {
            if (err) {
                console.log('publish failed:', err, guid);
            } else {
                console.log('published message with guid: ', err, guid);
            }
        });
    }
});

stan.on('error', (err) => {
    console.error(err);
});
```

```
published message with guid:  undefined TZ6PRKP5U8R8PPMBRSAU63
published message with guid:  undefined TZ6PRKP5U8R8PPMBRSAUDX
published message with guid:  undefined TZ6PRKP5U8R8PPMBRSAULR
published message with guid:  undefined TZ6PRKP5U8R8PPMBRSAUTL
published message with guid:  undefined TZ6PRKP5U8R8PPMBRSAV1F
published message with guid:  undefined TZ6PRKP5U8R8PPMBRSAV99
```

**Comment by AaronFriel** [comment]
@aricart here's the full function:

```ts

async function sendToSink(
  logger: Logger,
  connection: Stan,
  subject: string,
  envelope: Envelope,
) {
  logger.trace({ subject, envelope }, 'Publishing to NATS Sink');

  await new Promise((resolve, reject) => {
    connection.publish(
      subject,
      JSON.stringify(envelope),
      (err: unknown, ...args: unknown[]) => {
        if (err) {
          reject({ err, args });
        } else {
          resolve();
        }
      },
    );
  });
}
```

**Comment by aricart** [comment]
The handler has two arguments only, correct sig (in the index.d.ts file):
interface AckHandlerCallback { (err: Error | undefined, guid: string): void; }

**Comment by AaronFriel** [comment]
Yes, that shouldn't affect the first argument. The rest parameter `...args` will capture all additional arguments after the first and include them in the rejection object. The error is, however, a `{}`. We've been running NATS Streaming for five or six months and the code has functioned fine until recently, and we've hit this case once in a staging environment (the error was a `{}`). The decision then was to destroy the environment and recreate it, and we hadn't observed the error since.

We just today observed this in our production environment, and the error is an empty object.

**Comment by aricart** [comment]
Assuming everything is running on top of the world versions?
I don't see anywhere where an empty object is pushed into that argument. Could you do a cursory check on the lib where the system is running?

**Comment by kozlovic** [comment]
What would you get if the publish call times out? Reason I ask is that I wonder if as a temp fix @AaronFriel could simply check that if err is not a string, then it can be assumed that the publish was ok?

**Comment by AaronFriel** [comment]
Confirmed, the lib isn't corrupted. It's a perplexing error. We're on `2.2` of stan.js right now, haven't updated to `2.4`. NATS and NATS Streaming are at latest.

@kozlovic: I don't know what we would get if the publish times out, I think that's handled by the library?

I'm redeploying with the function rewritten as this and we're going to scale our system back up from zero. I'm also turning on `-SDV` in production.

```ts

async function sendToSink(
  logger: Logger,
  connection: Stan,
  subject: string,
  envelope: Envelope,
) {
  logger.trace({ subject, envelope }, 'Publishing to NATS Sink');

  await new Promise((resolve, reject) => {
    connection.publish(
      subject,
      JSON.stringify(envelope),
      (err: unknown, ...args: unknown[]) => {
        if (is.undefined(err)) {
          resolve();
        } else if (is.emptyObject(err)) {
          logger.fatal({ args, err }, 'Received empty object error on publishing to NATS Sink, treating as success.')
          resolve();
        } else {
          reject({ err, args });
        }
      },
    );
  });
}
```

**Comment by kozlovic** [comment]
@AaronFriel Sorry, question of timeout was addressed more to @aricart ..

**Comment by aricart** [comment]
@kozlovic a timeout is handled like this:
```
a.ah(new Error(ACK_TIMEOUT), peGUID);
```
where ACK_TIMEOUT is 'stan: publish ack timeout'

Regardless of the type, if no error occurred, the err argument would be `undefined`

**Comment by aricart** [comment]
So simple checks will flag it:
```
if (err) {
}
```

**Comment by aricart** [comment]
@AaronFriel would it be possible to bump your clients to the current versions - that version bumps up the protobuf library, which is the only place where something could be injected. Currently we test for an empty string, and all else is asssumed to be an error. If the protobuf library is acting up and returning some unexpected value (such as an empty object) it gets propagated to the client.

**Comment by AaronFriel** [comment]
@aricart Can do, I'm deploying a new version with a slight tweak because `is.emptyObject` is not the correct way to do the test. `new Error()` creates an object with non-enumerable properties, which our logging system picks up fine, but which `is.emptyObject` evaluates as true. So the test needs to be: `is.emptyObject(err) && !(err instanceof Error)`.

The last time we saw this in staging, a full system shutdown resolved everything, so this fluke might well disappear, which would be very unsatisfying for the amount of trouble it's caused.

**Comment by AaronFriel** [comment]
@aricart With additional logging, I haven't seen any errors logged since. This fluke issue appears to have disappeared again.

I haven't seen either of these `logger.fatal` messages get logged since deploying them:

```ts
export function isError(err: unknown): err is Error {
  return err instanceof Error;
}

function stringifyOwnProperties(err: unknown) {
  return JSON.stringify(err, Object.getOwnPropertyNames(err));
}

async function sendToSink(
  logger: Logger,
  connection: Stan,
  subject: string,
  envelope: Envelope,
) {
  logger.trace({ subject, envelope }, 'Publishing to NATS Sink');

  await new Promise((resolve, reject) => {
    connection.publish(
      subject,
      JSON.stringify(envelope),
      (err: unknown, ...args: unknown[]) => {
        if (is.undefined(err)) {
          resolve();
        } else if (is.emptyObject(err) && !isError(err)) {
          logger.fatal({ args, err, errProperties: stringifyOwnProperties(err) }, `Received error [${err}] empty object error on publishing to NATS Sink, treating as success.`)
          resolve();
        } else {
          logger.fatal({ args, err, errProperties: stringifyOwnProperties(err) }, `Received error [${err}] some non-empty object or error from NATS Streaming.`)
          reject({ err, args });
        }
      },
    );
  });
}
```

**Comment by AaronFriel** [comment]
Closing for now, can't replicate.
