### ISSUE TITLE
Need help to create a queue based on nats-streaming

### ISSUE THREAD

**Issue by ronezra3** [nats-io/stan.js#133]
Hello there, It's a great package, we are really excited to use it 
Need some help :)

I am trying to create a simple queue based on Nats streaming

My code look something like this - 

I have one file named index.js with this code

```
const nats = require('./nats-test');

var counter = 0;

nats.publish({ hello: "hello" })

nats.subscribe((msg) => {
    const newMsg = msg.getData();
    console.log(newMsg)
})

setInterval(() => {
    nats.publish({ hello: "hello" + ++counter })
}, 1000)
```

and the nats-test.js with this code

```
var stan = require('node-nats-streaming')


var stanClient = stan.connect('test-cluster', "testid1234",
    {
        url: "nats://localhost:4222"
    });


module.exports.subscribe = function (callback) {
    stanClient.on('connect', () => {
        var opts = stanClient.subscriptionOptions().setStartWithLastReceived();
        var subscription = stanClient.subscribe('topic', opts);
        subscription.on('message',callback);
    })

};


module.exports.publish = function (topic) {
    stanClient.on('connect', () => {
        stanClient.publish('topic', JSON.stringify(topic), function (err, guid) {
            if (err) {
                console.log('publish failed: ' + err);
            } else {
                console.log('published message with guid: ' + guid);
            }
        });
    })

};
```

1. I am always getting only the first "hello" msg, and never the "hello1" msg.

2. I need to do the on('connect') on every new publish and new message?

3. How can I export  the subscribe function and the publish function without the on('connect')?

4. Is there a need for acknowledge that the message is finished? 

5. Do I need to use the "durableName" for this use case?

**Comment by aricart** [comment]
@ronezra3 glad you are interested in NATS. There are a couple of things. First you are wrapping the library, which at this stage of your NATS learning is probably not a good idea.

Here's answers to your questions:
Q1: the reason why is when you are publishing, you are doing so to a new channel (`hello1`, `hello2`, etc). Your subscriber is simply waiting for messages on `hello`

Q2: The library is async, on `connect` lets the client know when the connection protocol has completed and the client can send messages. In the case of nats-streaming, when a client connects to the server it exchanges among other things, subjects that the instance of the client uses to interact with the nats-streaming-server. So yes, all interactions with the server must happen after the on `connect` event has fired.

Q3: This is an issue related to node library development, but I suspect you'll require some sort of notification mechanism to proxy the requirement. Whether it be by returning a promise or something else. In most cases you probably don't want to wrap the library until you are familiar with it and your needs. The library is very small and the API succinct. 

Q4: Normally when a message is received, it is auto-acknowledged. You can change that as describe here: https://github.com/nats-io/stan.js#message-acknowledgements-and-redelivery

Q5: Durable subscriptions are maintained on the server for a specific client id. If the client were to disconnect, on reconnecting, the server could resume the message stream where the client left off. More info here: https://github.com/nats-io/stan.js#durable-subscriptions

Your example re-written without the library in the middle simplifies your test:
```javascript
const STAN = require("node-nats-streaming");

var counter = 0;
const stan = STAN.connect("test-cluster", "testid1234");
stan.on('connect', () => {
    stan.publish("hello");

    const opts = stan.subscriptionOptions();
    opts.setStartWithLastReceived();
    const sub = stan.subscribe("hello", opts);
    sub.on('message', (msg) => {
        console.log(msg.getData());
    });

    setInterval(() => {
        stan.publish("hello", ++counter + "");
    }, 1000);
});
```

Note that in this case you are indeed sending messages to the streaming server, so all messages are persisted.
