### ISSUE TITLE
Allow passing an array of NATS Streaming connection urls as options.urls

### ISSUE THREAD

**Issue by PBug90** [nats-io/stan.js#135]
Currently users are forced to pass an url if using the options object:

```javascript
const opts = {
    url: 'nats://myserver-a:4222',
    urls: ['nats://myserver-a:4222','nats://myserver-b:4222']
}
this.natsConnection = nats.connect("some-cluster", "some-clientid", opts)
```
If you do not pass url in opts object, the default value ("nats://localhost:4222") will be used when making a connection attempt, regardless of an existing urls property in that same options object.

Since the cluster hosts are known before connecting, I would like to be able to pass them as an options property, just like the non-streaming javascript client allows you to do.

Adding both url and urls properties to the object works fine because the urls get passed through to the nats connection, but I want to do something like this:

```javascript
const opts = {
   urls: ['nats://myserver-a:4222','nats://myserver-b:4222','nats://myserver-c:4222']
}
this.natsConnection = nats.connect("some-cluster", "some-clientid", opts)
```

**Comment by aricart** [comment]
@PBug90  - the way the client connection works for nats.js, is you would do:
const opts = {
   url: 'nats://a:422', servers: ['nats://b:4222', 'nats://c.4222']
}
