### ISSUE TITLE
STAN clustering connection

### ISSUE THREAD

**Issue by johanlelan** [nats-io/stan.js#137]
# Misconception on STAN cluster connection.
Imagine that you have configured 3 STAN instances like this.
- localhost:14221
- localhost:14222
- localhost:14223

When you try to connect to the cluster with this connection `options` then you have **double** attempts.

```json
const options = {
  "maxReconnectAttempts": -1,
  "name": "nats-to-nats",
  "servers": [
    "nats://localhost:14222",
    "nats://localhost:15222",
    "nats://localhost:16222"
  ]
}
```

## Why ?
Because à this [line](https://github.com/nats-io/stan.js/blob/0fa6513eb09d7d3d28bed0fec7d48acbde6df57e/lib/stan.js#L128) `stan.js` forces the `url` property at DEFAULT_URL even if it's omitted. So the `createConnection` function of `nats.js` try first to connect to DEFAULT_URL then connect to random url into `options.servers`.

## But
It works nicely if you specify at least an instance with the `4222` port. Because it's the default one.

**Comment by aricart** [comment]
@johanlelan this is the way it works. The URL should always be provided or it defaults to the default server, then additional servers are provided via the servers option.
