### ISSUE TITLE
Reconnect issues while server restarts

### ISSUE THREAD

**Issue by akornatskyy** [nats-io/stan.js#138]
```txt
nats-streaming-server version 0.16.2, nats-server: v2.0.4
node: v13.1.0
node-nats-streaming: 0.2.6
```

```js
const stan = require('node-nats-streaming');

const sc = stan.connect('test-cluster', 'test');

sc.on('disconnect', () => console.log('disconnect'));
sc.on('reconnecting', () => console.log('reconnecting'));
sc.on('reconnect', () => console.log('reconnect'));
sc.on('connect', () => console.log('connect'));
sc.on('connection_lost', (err) => console.log('connection_lost ', err));
sc.on('close', () => console.log('close'));
sc.on('error', (err) => console.log('error, %o', err));
```

**Case 1**: Error: stan: connection lost due to PING failure

Stop server and wait for the js script to fail.

```log
connect
disconnect
reconnecting
reconnecting
reconnecting
reconnecting
connection_lost  Error: stan: connection lost due to PING failure
    at Timeout.pingFun (...node_modules\node-nats-streaming\lib\stan.js:358:68)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
close
```

**Case 2**: client has been replaced or is no longer registered

Restart server and wait for the js script to fail.

```txt
connect
disconnect
reconnecting
reconnect
connection_lost  client has been replaced or is no longer registered
close
```

**Comment by aricart** [comment]
@akornatskyy this behavior is the correct behavior. When you get a notification on close, you have to re-initialize the STAN connection, there's no reconnection after a `close` event.

**Comment by akornatskyy** [comment]
thanks, @aricart.

Case #1. It makes sense if server sends `close`, however this is not the case (the server is down). The client library give ups and doesn't tolerate reconnect count.

Case #2. After a short server restart the client library incorrectly handles handshake with the server, hence server complains 'the client has been replaced...', thus the client expected to handle reconnect correctly if it would lead to server error.

The problem is that there is no way to make re-connect work (as it is right now)... thoughts?

**Comment by kozlovic** [comment]
@akornatskyy The server does not send "close", but you stop the server so the underlying NATS connection gets closed at one point.

Also, if you use NATS Streaming server without a persistent store (default is memory only), then on server restart the server does not have any knowledge of any client. So if the streaming client's NATS connection reconnects and start to emit PINGs, the server will say that it does not know about this client. That will cause the library to report the connection as lost.

None of the streaming client library support auto-reconnect at this point (at the streaming layer, not NATS core layer). Once the "connection lost" streaming callback is invoked, it means that the user needs to recreate its streaming connection and subscriptions if applicable.
