### ISSUE TITLE
Accessing the incoming subject

### ISSUE THREAD

**Issue by syacko** [nats-io/stan.js#140]
I want to access the published NATS message subject in my subscriber.  When I display the subject it appears as an INBOX string.

![Screen Shot 2019-11-29 at 3 00 14 PM](https://user-images.githubusercontent.com/17324510/69892304-f613da00-12b8-11ea-86f1-52581f3ca1d2.png)

The actual subject is 
```
organization.1.version
```

Is there a way to retrieve the original subject created by the published inside the subscriber code?

**Comment by aricart** [comment]
You need to retrieve the subject from the stan message `msg.getSubject()` as the NATS subject will always be an inbox, as the server has a specific session with the client to process streaming messages.
