### ISSUE TITLE
Support for redeliveryCount method

### ISSUE THREAD

**Issue by sujeshthekkepatt** [nats-io/stan.js#142]
As per this MR https://github.com/nats-io/stan.go/pull/295 a redeliveryCount method is added in stan.go. Please add support for redeliveryCount

**Comment by aricart** [comment]
@sujeshthekkepatt I created a branch that adds the protobuf entry added, plus a method to access the value. Didn't write tests yet, but this should unblock you until it gets pushed.

**Comment by aricart** [comment]
Alright - I have a test, however the server still doesn't support the functionality so 'maybe' works is the status, until nats-streaming-server lands the feature.

**Comment by sambaran69** [comment]
Can we get this fix merged as the latest version of nats-streaming-server has support for RedeliveryCount (https://github.com/nats-io/nats-streaming-server/releases/tag/v0.17.0)?
