### ISSUE TITLE
Incorrect package.json import

### ISSUE THREAD

**Issue by avatarneil** [nats-io/stan.js#146]
When building a docker image for a package that has a dependency on `node-nats-streaming v0.3.0-0`:

```
Module not found: Error: Can't resolve '../package' in 'WORKING_DIR/node_modules/node-nats-streaming/lib'
```

Running Node v10.16.3

**Comment by aricart** [comment]
This seems to be an unexpected thing with docker, as it works properly on OS/Linux.
