### ISSUE TITLE
Is 0.3.0 gonna be released in NPM?

### ISSUE THREAD

**Issue by karliky** [nats-io/stan.js#160]
I've seen 0.3.0 under the releases section. 

In the project that I'm working on we are under `"node-nats-streaming": "^0.2.6",`. Is 0.3.0 gonna be released in NPM? Otherwise, I have to point to the git URL of this repo to use 0.3.0 which is not a common pattern.

**Comment by aricart** [comment]
@karliky 0.3.0 is in npm, but is not in latest, as the underlying nats library has an issue that affects tls connections. Always trust nats@latest for your production code.
