### ISSUE TITLE
Questions about proper management of durable queues

### ISSUE THREAD

**Issue by JAndritsch** [nats-io/stan.js#161]
nats-streaming-server version 0.17.0
stan.js version 0.3.0

I'm using a durable subscription in order to make sure messages are queued for clients when they temporarily lose connection to the server, so that any messages that were published during the disconnect get delivered once the client reconnects. I also need to support permanently removing those queues when a client intentionally disconnects from the server (as opposed to it happening from network instability). Below is a sample of the code I'm testing, followed by some questions I have based on the behavior I'm seeing.

```javascript

// New connection and subscription logic

import nats from 'node-nats-streaming';

const clientId = 'client-1';

const connection = nats.connect('some-server-id', clientId, {
  url: 'nats://127.0.0.1:4222',
  name: clientId,
});

connection.on('connect', () => {
  const options = connection.subscriptionOptions();
  //options.setDeliverAllAvailable(); // <------- This gives me ALL messages in the queue for this subscription.
  options.setStartWithLastReceived(); // <------- This gives me the LAST message that I've already ACK'ed.
  options.setManualAckMode(true);
  options.setDurableName(clientId);

  const subscription = connection.subscribe('my-channel', options);

  subscription.on('message', (message) => {
    console.log('We got a message: ', message);
    message.ack();
  });
});

// Sometime later I want to close my connection with intent to remove the durable queue and
// start a fresh, new queue the next time I connect with the same clientId.
subscription.once('unsubscribed', () => {
  connection.close();
});
// This does not seem to remove the queue from the server because when I reconnect with the same
// clientId, previously delivered messages are being redelivered.
subscription.unsubscribe();

```

Questions:

1. Why does `setDeliverAllAvailable()` replay the ENTIRE message history from my durable queue? The docs and example code show this option being used when describing how to resume from where a client left off. I'm not seeing that behavior. What I've found is that `setStartWithLastReceived()` is closer to what I want, but it sends me the LAST message that I've already acknowledged instead of sending me the FIRST unacknowledged message. I've also verified that I am receiving the same sequence IDs over and over. What's also confusing is that the docs on https://docs.nats.io/nats-streaming-concepts/channels/subscriptions/durable say the starting position is ignored when resuming a durable subscription, so I'm confused as to why I see completely different behavior when providing a starting position at all.

2. What is the proper way to close a connection and unsubscribe a subscription? The code suggests `Subscription#unsubscribe()` is meant to remove a durable subscription from the server and `Subscription#close()` is to temporarily halt receiving messages on that subscription until the client wants to resume it, but retain its durability. The same docs on http://docs.nats.io say the following: "When the application wants to stop receiving messages on a durable subscription, it should close - but not unsubscribe - this subscription. When the application wants to delete the subscription, it must unsubscribe it.". I'm not seeing this behavior when I call `unsubscribe()`. Issue #141 points at `sub.close()` being the correct method to call for the behavior I desire, but the docs seem to suggest that's not right.

**Comment by JAndritsch** [comment]
I think I found my issue and answers.

My code issue:

I had two subscriptions being created that used the same value for the durable name. I suspect this was the issue. After changing the code to use unique names for each durable, things worked as expected.

Takeaways:

1. `Subscription#unsubscribe()` is the correct method to call when you intend to remove a durable queue from the server.

2. Specifying a starting position when subscribing to a durable queue is not necessary because the server tracks the information for me. My tests showed the server does the right thing without me having to specify starting position at all. I think it would be helpful to update the documentation and code samples on https://github.com/nats-io/stan.js/#durable-subscriptions, because that example makes it look like you must call `opts.setDeliverAllAvailable()` when configuring a durable sub.

**Comment by kozlovic** [comment]
> Specifying a starting position when subscribing to a durable queue is not necessary because the server tracks the information for me.

True once the durable subscription is created. But the start position is used when the server handles the subscription request for the first time: https://docs.nats.io/nats-streaming-concepts/channels/subscriptions/durable

**Comment by JAndritsch** [comment]
That makes sense. Thank you for clarifying!
