### ISSUE TITLE
Nats typescript; Possibly incorrect typing

### ISSUE THREAD

**Issue by shanurrahman** [nats-io/stan.js#163]
The typings file says that the third parameter should be StanOptions but in the example file we are providing a string with server's location
Typings file `index.d.ts [connect method]`
```export function connect(clusterID: string, clientID: string, opts?: StanOptions): Stan;```

Code for connecting to nats streaming server, here server is a string not StanOptions
Example file `stan-pub.js`
```const sc = STAN.connect(clusterID, clientID, server)```

One more issue with typings, in the example file we are doing something like this, but the typescript typings doesnot have a durableName for SubscriptionOptions. I am on version "node-nats-streaming": "^0.3.2"
```
const opts = sc.subscriptionOptions()
opts.setDurableName(options.durableName)
```

**Comment by aricart** [comment]
Indeed, the options can be the `StanOptions | string | number`
