### ISSUE TITLE
Subscription ready event not emitted

### ISSUE THREAD

**Issue by oncicaradupopovici** [nats-io/stan.js#166]
When creating a non-durable subscription with StartPosition.NEW_ONLY I don't receive the 'ready' event notification.

I need to expose a promise based api over the stan subscribe fn, the promise should resolve when the 'ready' notification is received, like this:

return new Promise((resolve, reject) => {
        const subscription = client.subscribe(subject, natsOpts)
        subscription.on('ready', () => {
            //This event never fires for some reason!!!!!!!!!
            resolve(subscription)
        })

**Comment by aricart** [comment]
Many of the tests for stan.js rely on this. I did a simple one:

```javascript
  it('sub emits ready', (done) => {
    const stan = STAN.connect(cluster, nuid.next(), PORT)
    stan.on('connect', () => {
      const subject = nuid.next()
      const opts = stan.subscriptionOptions()
      opts.setStartAt(STAN.StartPosition.NEW_ONLY)
      const p = new Promise((resolve, reject) => {
        const sub = stan.subscribe(subject, '', opts)
        sub.on('ready', () => {
          resolve()
        })
      })
      p.then(() => {
        console.log('ready was fired')
        done();
      })
    })
  })
```
> ready was fired

Is it possible that your connection didn't happen? Set your subscription on the `connect` event.

**Comment by oncicaradupopovici** [comment]
Thank you for your reply, I must be doing something wrong then :)
The Nats server logs my subscription as successful, and indeed if I resolve my promise without waiting for the ready event, my subscription works just fine, with the cost of introducing a race condition.
 
I create a singleton connection during application start, and upon certain requests, I use this connection to publish or subscribe to certain subjects, can this be a problem? Can a single connection be used for the whole server?

**Comment by aricart** [comment]
The subscription also emits an `error` event. Can you listen for that and see if you get something there?

**Comment by oncicaradupopovici** [comment]
I finally figured it out, it was a race condition on my side, I was not awaiting the "connect" event on the   connection :)

Thank you for your support!
