### ISSUE TITLE
export SubscriptionOptions as function from stan.js

### ISSUE THREAD

**Issue by meabed** [nats-io/stan.js#170]
Thank for the awesome work!
I would be very helpful if SubscriptionOptions could be exported and used without Connection, as currently you have to connect then pass by the connection reference and get subscriptionOptions.

I am mirroring the method in my codebase to have this easier to access and work with.
```

// hack because its not exported from the driver
export function getQueueSubscriptionOptions(): SubscriptionOptions {
  return {
    durableName: '',
    maxInFlight: 16384,
    ackWait: 30 * 1000,
    startPosition: StartPosition.LAST_RECEIVED,
    startSequence: undefined,
    startTime: undefined,
    manualAcks: false,

    setStartWithLastReceived(): SubscriptionOptions {
      this.startPosition = StartPosition.LAST_RECEIVED;
      return this;
    },
    setAckWait(millis: number): SubscriptionOptions {
      this.ackWait = millis;
      return this;
    },
    setDeliverAllAvailable(): SubscriptionOptions {
      this.startPosition = StartPosition.FIRST;
      return this;
    },
    setDurableName(durableName: string): SubscriptionOptions {
      this.durableName = durableName;
      return this;
    },
    setManualAckMode(tf: boolean): SubscriptionOptions {
      this.manualAcks = tf;
      return this;
    },
    setMaxInFlight(n: number): SubscriptionOptions {
      this.maxInFlight = n;
      return this;
    },
    setStartAt(startPosition: StartPosition): SubscriptionOptions {
      this.startPosition = startPosition;
      return this;
    },
    setStartAtSequence(sequence: number): SubscriptionOptions {
      this.startPosition = StartPosition.SEQUENCE_START;
      this.startSequence = sequence;
      return this;
    },
    setStartAtTimeDelta(millis: number): SubscriptionOptions {
      this.startPosition = StartPosition.TIME_DELTA_START;
      // noinspection JSUnresolvedFunction
      // server expects values in ns
      this.startTime = millis * 1000000;
      return this;
    },
    setStartTime(date: Date): SubscriptionOptions {
      this.startPosition = StartPosition.TIME_DELTA_START;
      // server expects values in ns
      this.startTime = (Date.now() - date.valueOf()) * 1000000;
      return this;
    },
  };
}

```

So if it this feasible - would be great to export it - as it would be working with driver options easier..

Thank again, you guys are awesome - I love Nats 👍

**Comment by aricart** [comment]
@meabed it will be exported in a strange way - because the typescript definition exports an interface, I want to make sure that this change doesn't affect other users. Instead of exporting the type, I am going to export a function as `NewSubscriptionOptions()` which returns a `SubscriptionOptions` instance.

**Comment by meabed** [comment]
Make even more sense :)
Awesome 
On another note - I have promisified the nats and the steaming server clients and events and multi-ton pattern connection hashmap, if that’s something you would guys accept contribution to, I would open a PR. I know there is v2 alpha kinda of branch and I hope also to see it out soon :)

**Comment by aricart** [comment]
> Make even more sense :)
> Awesome
> On another note - I have promisified the nats and the steaming server clients and events and multi-ton pattern connection hashmap, if that’s something you would guys accept contribution to, I would open a PR. I know there is v2 alpha kinda of branch and I hope also to see it out soon :)
> Keep up the great work 👍

For promised versions of nats, take a look at https://github.com/nats-io/nats.ts, v2 branch changes many things. Also, nats.js has a v2 branch (as does this repo). The async apis will go one more rev, currently working on the nats.deno which will add Deno support. - Missing yet but in the works is iterator support in the subscriptions.

**Comment by aricart** [comment]
`npm install node-nats-streaming@next` to get a build.
