### ISSUE TITLE
connection_lost and error events emit error as a string

### ISSUE THREAD

**Issue by satazor** [nats-io/stan.js#171]
The `error` parameter from the `connection_lost` event sometimes is an Error instance, sometimes is a string. 

It seems we are missing a `new Error` [here](https://github.com/nats-io/stan.js/blob/b526ab719792e59a2e7e31b28da2544b2d6b938c/lib/stan.js#L292) as well as [here](https://github.com/nats-io/stan.js/blob/b526ab719792e59a2e7e31b28da2544b2d6b938c/lib/stan.js#L324) as `getError` always returns a string.

**Comment by aricart** [comment]
@satazor  - thanks for sleuthing.

**Comment by aricart** [comment]
Fixed in acf810dcbe9aab161ed893d6a39e84841e1c9152
