### ISSUE TITLE
Re-Subscribe on connection lost or error

### ISSUE THREAD

**Issue by meabed** [nats-io/stan.js#174]
Hey awesomes 👋 

Currently if you subscribe and exception occurred or connection lost, there is no mechanism to auto re-subscribe to message subject. I am not sure if this is available or possible, I was thinking to wrap all subscription with some sort of exception handlers and connection retry subscription - not sure if this good idea :) 

Would appreciate any input from the team.

Thanks a lot of the great platform NATS.

**Comment by aricart** [comment]
@meabed on `connection lost`, the client is no longer good. The initial handshake exchanges mappings that it can use to interact with the server. After a connection lost, that map is no longer valid, so they need to be re-setup, really the easiest way is really to just restart your service. Assuming there's no user behind the keyboard, the normal startup sequence should land you where you were. If you are using durables and queue groups, you should be able to join a shared session and continue where you left off.
