### ISSUE TITLE
If it’s streaming client, how can I send and receive node stream?

### ISSUE THREAD

**Issue by reklatsmasters** [nats-io/stan.js#176]
Just example, how can I send and receive file? It more looks like simplified task queue.

**Comment by aricart** [comment]
not quite sure I understand your question. NATS is a messaging platform, and as such, it is payload agnostic. This means that a message can carry any payload. NATS-Streaming is a persistence technology built on top of NATS. NATS Streaming is intended for persisting data that can be read and processed at a later time.

If you want to move files between nodes, etc. You don't need NATS streaming. You can easily implement a service that listens for requests to some particular data, and in response, returns it. The data for the response could be sent over several messages.

**Comment by aricart** [comment]
The following documentation may be useful as an introduction to the system:
[NATS](https://docs.nats.io/nats-concepts/intro)
[NATS Streaming](https://docs.nats.io/developing-with-nats-streaming/streaming)

**Comment by aricart** [comment]
@reklatsmasters Feel free to reopen this issue if you have additional questions. You can also join our [slack community](https://slack.nats.io/)
