### ISSUE TITLE
Describe connection options in readme

### ISSUE THREAD

**Issue by alextes** [nats-io/stan.js#179]
It's unclear how to connect now. There's an example but it is hard to tell from the strings used what the strings are specifying, in specific this is all I can find

```js
const sc = require('node-nats-streaming').connect('test-cluster', 'test')
```

And a reference to `stanConnection` which isn't defined anywhere.

**Comment by aricart** [comment]
@alextes, you are absolutely right. If getting started with NATS and STAN simply looking at the README is not going to really do it. Let's see if I can help here while getting you up to speed:

Some of the basics not covered on the client info:
- The nats-streaming client embeds a nats-client, as the nats-sever is really another client of a nats-server. So when you connect you are connecting to a nats-server and publishing messages that a nats-streaming-server will get. By default, the embedded nats-client will connect to `localhost:4222`. The nats-streaming-server embeds a nats-server, and by default, it starts one listening on `localhost:4222`.
- The nats-streaming-server uses the concept of a _cluster_id_ to create logical groupings of servers and clients.
- Each client in nats-streaming must have a unique id. This enables the nats-streaming server to identify a particular client and manage its state.

Now back to the magic above:

`require('node-nats-streaming')` imports the library, which exports a `connect` function. The `connect` function takes 2 or 3 arguments: `connect("streaming_cluster_id", "client_id", {})`.
The `streaming_cluster_id` references the nats-streaming-server cluster_id, `client_id` the unique client you assign to the client. In the example, the options are elided, which means that the nats connection will all be defaulted, resulting in a connection attempt at `nats://localhost:4222`. For more info on options that you can pass, see https://github.com/nats-io/stan.js/#connect-options and https://github.com/nats-io/nats.js#connect-options. 

The return value of `connect` is a stan connection, which then you can use to interact with the remote stan server.

**Comment by aricart** [comment]
This nats-streaming documentation has a pre-requisite, understanding of NATS, which you can find here:
https://docs.nats.io/developing-with-nats/developer

While the stan.js client is in javascript, the APIs concepts are exactly the same. You may also want to take a look at:

https://docs.nats.io/developing-with-nats-streaming/streaming

**Comment by alextes** [comment]
Hi @aricart appreciate the elaborate reply.
Sounds like some of this could be in the README!

Perhaps a section on connecting based on what you just explained.

```
## Connecting

### connect(cluster_id, client_id, opts?)
By default the client tries to connect to `localhost:4222`.

- cluster_id, ???
- client_id, unique identifier used by NATS to identify the connecting client

#### opts
- ...
```

I did find the description of the parameters in the NATS docs on the website like you linked. One step further now with a refused connection. Nice to see some types too. They helped a bit 👍 .

**Comment by aricart** [comment]
Just in case - The async client (nats.ts) is not compatible with stan.js. The peer for stan.js is nats.js.

**Comment by aricart** [comment]
Also if you are getting a connection refused, the nats-connection is failing. Depending on the OS you are using, you may have to specify `127.0.0.1:4222` instead...

**Comment by alextes** [comment]
Got it working using the `url` option from nats.js 🙌 . Took some figuring out but with the protocol and port specified the client was happy to connect.

Connecting to NATS on Kubernetes actually. Not running anything locally.

If you're interested in improving the docs this can be open and perhaps you can suggest what kind of PR you'd accept, if not, fine too, and let's close this issue.

**Comment by aricart** [comment]
👏 🎆 - currently, the client is documented the same way that other clients are. With that said, it can be daunting. We have very good dev docs for nats in docs.nats.io which present snippets in the various supported languages, but for stan not as much. Currently, nats-streaming-server is to be replaced by [jetstream](https://github.com/nats-io/jetstream), so not sure how much better we can make it. I will add some additional hints on the README, to offer pointers. Keeping this open until then.

**Comment by alextes** [comment]
Ah neat. That's fine. Knowing efforts are pointed at jetstream is already helpful. Happen to have a rough, non-commital idea of when that comes out of technical preview?

**Comment by aricart** [comment]
Q3/Q4 likely.

**Comment by aricart** [comment]
Support of JS is already built into current generation NATS client in JavaScript.
