### ISSUE TITLE
NATS Redelivering Limit

### ISSUE THREAD

**Issue by michielswaanen** [nats-io/stan.js#180]
Hey,

Does the node-nats-streaming library support setting a redelivering limit?
Can't seem to find anything about this.

**Comment by aricart** [comment]
@michielswaanen 

nats-streaming clients don't support such a feature that I am aware of - @kozlovic  can confirm.

It doesn't make a sense for a persistent system to have such a limit, as the intention is to process all messages if the message has some data that prevents its processing, the application likely should implement some sort of _dead letter queue_ where the message is sent to another channel for additional processing or inspection, this, of course, means that the forwarding client has to ack the message.

**Comment by michielswaanen** [comment]
Ok thanks! A dead letter queue sounds good, I'm kinda new to event based stuff. 

This can be closed 😁
