### ISSUE TITLE
Cannot access embedded NATS connection from Stan

### ISSUE THREAD

**Issue by SigfridStjarnholm** [nats-io/stan.js#182]
Im having some trouble trying to access the embedded NATS connection from Stan. I need to do this as i want to use request-reply, which is not supported in NATS Streaming. Im using Typescript. 

If i use
import nats, { Stan } from "node-nats-streaming";
...
client: Stan = nats.connect(clusterId, clientId, { url });

there is no way to access the NATS client, as far as i can see in the documentation? If I understood the stan.go documentation correctly, this embedded NATS client could be accessed by **_client.NatsConn()_**

**Comment by SigfridStjarnholm** [comment]
Ah, I found a solution in a separate issue. Maybe it could be documented som more? 
https://github.com/nats-io/stan.js/issues/116#issuecomment-578049012

I created a separate NATS connection and used that to connect to STAN.

**Comment by aricart** [comment]
Yes, connections created by the library are not supposed to be reached into.  As you figured out, if you want to share it, you have to create it and provide it as an option.
