### ISSUE TITLE
stan.js doesn't try to reconnect

### ISSUE THREAD

**Issue by nimamahmoudi** [nats-io/stan.js#183]
I have the following code, running on `node-nats-streaming@0.3.2`, which successfully connects to server setup using docker using `nats-streaming:0.18-alpine` image:

```
const STAN = require('node-nats-streaming')

const { NATS_CONN_URL } = require('../config')

let url = NATS_CONN_URL
let sc = STAN.connect('mail-cluster', 'node-worker', {
  url,
})

// emitted whenever there's an error. if you don't implement at least
// the error handler, your program will crash if an error is emitted.
sc.on('error', (err) => {
  console.log("[NATS] Error:", err)
})

// connect callback provides a reference to the connection as an argument
sc.on('connect', () => {
  console.log(`[NATS] connected`)
})
 
// emitted whenever the client disconnects from a server
sc.on('disconnect', () => {
  console.log('[NATS] disconnect')
})
 
// emitted whenever the client is attempting to reconnect
sc.on('reconnecting', () => {
  console.log('reconnecting')
})
 
// emitted whenever the client reconnects
// reconnect callback provides a reference to the connection as an argument
sc.on('reconnect', () => {
  console.log(`[NATS] reconnect`)
})
 
// emitted when the connection is closed - once a connection is closed
// the client has to create a new connection.
sc.on('close', function () {
  console.log('[NATS] close')
})
 
// emitted whenever the server returns a permission error for
// a publish/subscription for the current user. This sort of error
// means that the client cannot subscribe and/or publish/request
// on the specific subject
sc.on('permission_error', function (err) {
  console.error('[NATS] got a permissions error', err.message)
})
```

However, when there are network connectivity issues, there are no reconnect attempts, it just fails with the following output:

```
[NATS] connected
[NATS] close
```
Am I doing anything wrong?

**Comment by aricart** [comment]
The `connection_lost` event is triggering and closing the connection.
If I copy your code, and add a connection lost handler, you can see that this is triggering (at least on my side it is)
```javascript
sc.on('connection_lost', function() {
  console.error('[STAN] connection lost')
});
```
```bash
[NATS] connected
[NATS] disconnect
reconnecting
reconnecting
reconnecting
reconnecting
reconnecting
reconnecting
reconnecting
reconnecting
reconnecting
[STAN] connection lost
[NATS] close
```

One thing to keep in mind is that by default the max reconnect attempts is set to -1, which means it will try forever to reconnection. But the one wrinkle is that the `stanPingInterval` is set to 5s, and `stanMaxPingOut` is set to 3. This means that even though the underlying nats connection is set to re-try forever, the stan client will consider the connection lost if the above threshold is not met. The server, by the way [has a similar logic](https://docs.nats.io/nats-streaming-server/configuring/cfgfile). - the properties of interest there are `hb_interval` and `hb_fail_count`.

On core NATS a client can be configured to reconnect forever, and on connect, it will re-send any subscriptions it had. On stan, there's s protocol behind the subscriptions and clients cannot resume once a `connection_lost` has happened as the client will have to renegotiate the subscription protocol.

One thing that you can do is, create a nats connection outside of the stan connect call, and pass it to the stan connect via the `nc` property. This connection is now yours and will retry forever to reconnect. You can then use the `connection_lost` handler to re-trigger the stan connection sequence and resume.

**Comment by aricart** [comment]
Here's a better example that will help you understand what is going on:
```javascript
const STAN = require('node-nats-streaming')
const nats = require("nats");

const nc = nats.connect({waitOnFirstConnect: true, maxReconnectAttempts: -1, encoding: "binary"});
nc.on("connect", () => {
	nc.on('error', (err) => {
	  console.log("[NATS] Error:", err)
	})

	// connect callback provides a reference to the connection as an argument
	nc.on('connect', () => {
	  console.log(`[NATS] connected`)
	})
	 
	// emitted whenever the client disconnects from a server
	nc.on('disconnect', () => {
	  console.log('[NATS] disconnect')
	})
	 
	// emitted whenever the client is attempting to reconnect
	nc.on('reconnecting', () => {
	  console.log('NATS reconnecting')
	})
	 
	// emitted whenever the client reconnects
	// reconnect callback provides a reference to the connection as an argument
	nc.on('reconnect', () => {
	  console.log(`[NATS] reconnect`)
	})
	 
	// emitted when the connection is closed - once a connection is closed
	// the client has to create a new connection.
	nc.on('close', function () {
	  console.log('[NATS] close')
	})
	 
	// emitted whenever the server returns a permission error for
	// a publish/subscription for the current user. This sort of error
	// means that the client cannot subscribe and/or publish/request
	// on the specific subject
	nc.on('permission_error', function (err) {
	  console.error('[NATS] got a permissions error', err.message)
	})
	
	doStan(nc);
});

function doStan(nc) {
	let sc = STAN.connect('test-cluster', 'node-worker', {nc: nc})

	// emitted whenever there's an error. if you don't implement at least
	// the error handler, your program will crash if an error is emitted.
	sc.on('error', (err) => {
	  console.log("[STAN] Error:", err)
	})

	// connect callback provides a reference to the connection as an argument
	sc.on('connect', () => {
	  console.log(`[STAN] connected`)
	})
	
	// emitted when the connection is closed - once a connection is closed
	// the client has to create a new connection.
	sc.on('close', function () {
	  console.log('[STAN] close')
	})
	 
	// emitted whenever the server returns a permission error for
	// a publish/subscription for the current user. This sort of error
	// means that the client cannot subscribe and/or publish/request
	// on the specific subject
	sc.on('permission_error', function (err) {
	  console.error('[NATS] got a permissions error', err.message)
	})

	sc.on('connection_lost', function() {
		console.error('[STAN] connection lost')
		setTimeout(()=>{
			doStan(nc);
		});
	});
}
```

**Comment by aricart** [comment]
With the above example, you can see what is going on:
```bash
[STAN] connected
[NATS] disconnect
NATS reconnecting
NATS reconnecting
NATS reconnecting
[NATS] reconnect
[STAN] connection lost
[STAN] close
[STAN] connected
[NATS] disconnect
NATS reconnecting
NATS reconnecting
NATS reconnecting
NATS reconnecting
NATS reconnecting
NATS reconnecting
NATS reconnecting
NATS reconnecting
[NATS] reconnect
[STAN] connection lost
[STAN] close
[STAN] connected
[NATS] disconnect
NATS reconnecting
NATS reconnecting
```

**Comment by aricart** [comment]
Feel free to reopen this issue if you have more questions.

**Comment by nimamahmoudi** [comment]
Thanks for the detailed explanation. All seems fine, I modified my code to trigger the creation of a new connection on [STAN] close event. Now, everything seems to work fine.

**Comment by nimamahmoudi** [comment]
It is weird though that I am not seeing `reconnecting` in my output. Although, it might be that I am using `node:10-slim` image on Docker.

**Comment by rabeeshcharles** [comment]
try {

    var streamConnectOptions = {
        waitOnFirstConnect: true,
        verbose: true,
        url: 'http://nats:port' // Nats Streaming
    };

    const STAN = require('node-nats-streaming')
    const nats = require("nats");

  
    const nc = nats.connect({ servers:"http://nats:port", waitOnFirstConnect: true, maxReconnectAttempts: -1, encoding: "binary" });
    nc.on("connect", () => {
        nc.on('error', (err) => {
            console.log("[NATS] Error:", err)
        })

        // connect callback provides a reference to the connection as an argument
        nc.on('connect', () => {
            console.log(`[NATS] connected`)
        })

        // emitted whenever the client disconnects from a server
        nc.on('disconnect', () => {
            console.log('[NATS] disconnect')
        })

        // emitted whenever the client is attempting to reconnect
        nc.on('reconnecting', () => {
            console.log('NATS reconnecting')
        })

        // emitted whenever the client reconnects
        // reconnect callback provides a reference to the connection as an argument
        nc.on('reconnect', () => {
            console.log(`[NATS] reconnect`)
        })

        // emitted when the connection is closed - once a connection is closed
        // the client has to create a new connection.
        nc.on('close', function () {
            console.log('[NATS] close')
        })

        // emitted whenever the server returns a permission error for
        // a publish/subscription for the current user. This sort of error
        // means that the client cannot subscribe and/or publish/request
        // on the specific subject
        nc.on('permission_error', function (err) {
            console.error('[NATS] got a permissions error', err.message)
        })

        doStan(nc);
    });

    function doStan(nc) {
        let sc = STAN.connect('test-cluster', 'node-worker', { nc: nc })

        // emitted whenever there's an error. if you don't implement at least
        // the error handler, your program will crash if an error is emitted.
        sc.on('error', (err) => {
            console.log("[STAN] Error:", err)
        })

        // connect callback provides a reference to the connection as an argument
        sc.on('connect', () => {
            console.log(`[STAN] connected`)
        })

        // emitted when the connection is closed - once a connection is closed
        // the client has to create a new connection.
        sc.on('close', function () {
            console.log('[STAN] close')
        })

        // emitted whenever the server returns a permission error for
        // a publish/subscription for the current user. This sort of error
        // means that the client cannot subscribe and/or publish/request
        // on the specific subject
        sc.on('permission_error', function (err) {
            console.error('[NATS] got a permissions error', err.message)
        })

        sc.on('connection_lost', function () {
            console.error('[STAN] connection lost')
            setTimeout(() => {
                doStan(nc);
            });
        });
    }
} catch (error) {
    console.log('Catch Error ', error)

}


Above Code Producing Error 

Catch Error  TypeError: nc.on is not a function
    at Object.<anonymous> (C:\Users\rabeeshv\Desktop\Rabeessh\Samples\Code Samples\nats\natsStreaming.js:14:8)
    at Module._compile (internal/modules/cjs/loader.js:1155:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by rabeeshcharles** [comment]
After Using this package "nats@1.4.12"
Previous error is gone but connect event is not fired
```
 nc.on("**connect**", () => {

```

**Comment by aricart** [comment]
if you are creating the connection outside of stan, it probably is not surfacing. If you have stan do it's own connection, do you get the event?

**Comment by aricart** [comment]
Also - if you are starting work using stan.js, you should really stop and start looking at jetstream instead, which is supported directly by all our current javascript clients. https://github.com/nats-io/nats.deno/blob/main/jetstream.md

**Comment by rabeeshcharles** [comment]
Great..Let me give a try...
