### ISSUE TITLE
Is it safe to use the client concurrently? What should I watch out for?

### ISSUE THREAD

**Issue by gnarea** [nats-io/stan.js#184]
Hi,

I have an API where some `POST` endpoints will publish data to NATS Streaming (which will be consumed by a background queue) and one WebSockets endpoint will stream some events from NATS Streaming (produced by another background queue). For performance reasons, I'd like to create just one stan.js connection per process in the web server, so that the same connection will be shared across HTTP requests which will be publishing and subscribing to different channels. Would that be safe?

I've created a simple wrapper around stan.js to expose the subset of the functionality I'm using and to make unit testing easier. This wrapper also takes care of establishing the connection lazily (on the first publish/subscription), and reconnecting lazily when the connection is closed or lost (by listening to the `close`  and `connection_lost` events, respectively).

When we can't connect to NATS Streaming or we can't publish/subscribe, the error will be handled gracefully on the endpoints by returning an HTTP 500 and, if we received a `close`/`connection_lost` event, our stan.js wrapper will try to create a new connection lazily on the next request (using the same client id, which is unique to the process). By contrast, the same error would cause the background queues to error out (and be restarted).

In case it's relevant, I'm using Kubernetes and each process will run on its own container (so there are no worker pools). I'm currently assuming it's not safe to reuse the connection and so I'm connecting/disconnecting in each request (and using the client for one thing only: publishing or subscribing to exactly one channel).

Thanks!

**Comment by aricart** [comment]
If you are using the nats.ws library, the stan.js lib doesn't support it.
Stan.js requires nats.js 1.x.

A single connection will only guarantee order by publisher. Furthermore in
an async API different subscriptions may resolve messages spuriosly.  So if
you are relying on when the message gets presented, better check that your
design. Only way for that would be only using callbacks, as invocation
happens as the message is parsed.

**Comment by gnarea** [comment]
Thanks for the explanation @aricart!

Makes sense. Since I'm using async/await, I should be creating a dedicated connection for each subscription in that case, which fortunately is what I've done so far.

Also, just to clarify -- when you say:

> If you are using the nats.ws library, the stan.js lib doesn't support it. Stan.js requires nats.js 1.x.

Do you mean that NATS Streaming could theoretically support my single-connection scenario reliably, but it's just not supported by stan.js at the moment?

**Comment by aricart** [comment]
If a v2 compatible client is created for streaming is made.  Right now the priority is for JetStream. Let's see if the schedule allows for a nats streaming wrapper.

With a new client, nats+streaming would be supported on all the v2 platforms, ws, tcp, and Deno!
