### ISSUE TITLE
noEcho option not supported

### ISSUE THREAD

**Issue by michielswaanen** [nats-io/stan.js#185]
Hey

I was looking through the docs and saw that the `noEcho` option was available. ([Reference](https://docs.nats.io/developing-with-nats/connecting/noecho))
It looks like the stan.js library doesn't support this feature? I looked into the code and found this:
https://github.com/nats-io/stan.js/blob/69d293e001b2b73587e3e23f867d7fc5fa972b0e/index.d.ts#L40-L44

Why is this the case? Is there another way to disable message echo'ing?

**Comment by aricart** [comment]
The noEcho option is a core nats option.  For nats streaming there's no concept like that.  You are simply replaying messages, there's no notion that you may have been the sender.
