### ISSUE TITLE
Updates from nats.js

### ISSUE THREAD

**Issue by meabed** [nats-io/stan.js#199]
Thank you so much for the great work you put in here. I wanted to ask if there any plan to release updates soon as I see the nats.js having some updates lately.

I'm happy to help in those as well.

Thank you.

**Comment by aricart** [comment]
@meabed the stan.js client is currently not a priority, since STAN functionality is superseded by JetStream. If I get some cycles I might, but would suggest that you start looking into JetStream :)

**Comment by meabed** [comment]
Thank you! Will check it out :)
