### ISSUE TITLE
NATS connection closed on throwing new Error

### ISSUE THREAD

**Issue by rajuAhmed1705** [nats-io/stan.js#200]
I'm using Nats streaming, node-nats-streaming inside my Nodejs application.
I have two services running on the Kubernetes cluster, talking to each other using Nats.
The problem is when an error happens inside my listener, the nats client gets disconnected and never shows up again in the clients list of the Nats server.
The client is running inside the Kubernetes cluster, connecting to its database, but it lost its connection to Nats streaming and never gets reconnected.

```
  subscription.on('message', (msg: Message) => {
      const data = msg.getData();

      const order = Order.findById(data.orderId);

      if (!order) {
          // by throwing this error NATS client gets disconnected, and never connects again
        throw new Error('Order not found');

      }

      // doing some modification with the order object 

      msg.ack();
    });
```

My question is, is it the default behavior of the node-nats-streaming client? and how can I solve the issue.
Thanks in advance.

**Comment by aricart** [comment]
You cannot throw unchecked exceptions without some sort of handler somewhere. If you find that type of code acceptable, then at the very least you must implement `process.on('uncaughtException')`. 

Also, in the case above, you'll keep crashing, as the nats-streaming-server is going to be giving you the same message over and over again.

**Comment by rajuAhmed1705** [comment]
I wanted to handle the concurrency update issue by introducing version numbers in my schema. I solved it another way. thank you.

**Comment by ChinmayaTelstra** [comment]
Hi @rajuAhmed1705 
Can you please provide the solution you took to resolve this issue? Im facing the same issue and my code is very similar to yours. I keep getting below error on my service which is listenning to expiration message and cant find the Order.


2024-01-17 04:55:54:5554 info: Common Module [Base Listener]: The Message received is expiration:complete / orders-service
2024-01-17 04:55:54:5554 info: Orders service [Index] - Connected to Orders MongoDb!
2024-01-17 04:55:54:5554 info: Orders service [Index] - Listening on port! 3000
Error: Orders service [ExpirationCompleteListener]: Order not found
    at ExpirationCompleteListener.<anonymous> (/app/src/events/listeners/expiration-complete-listener.ts:15:10)
    at Generator.next (<anonymous>)
    at fulfilled (/app/src/events/listeners/expiration-complete-listener.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[ERROR] 04:55:54 Error: Orders service [ExpirationCompleteListener]: Order not found
