### ISSUE TITLE
Can I use this in a React Native app?

### ISSUE THREAD

**Issue by saikarthikp9** [nats-io/stan.js#201]

**Comment by bahmanbs** [comment]
@saikarthikp9 tanks to the [Mehrdad](https://github.com/thegreatzeus), now there is a repository that includes a working example in react native [here](https://github.com/thegreatzeus/NATS-WS-React-Native-Example)

**Comment by aricart** [comment]
@saikarthikp9  You shouldn't be using stan.js (use jetstream instead)

**Comment by bahmanbs** [comment]
@aricart i need to comunicate with nats, not jetstream, i do not need persistence but only pub sub.
whas is you reason for this? guide me please.

**Comment by Jarema** [comment]
stan.js is a client for old `nats-streaming` persistence solution that was replaced by `jetstream`.

For both Core NATS (pub/sub request/reply) and JetStream, use
https://github.com/nats-io/nats.ws

The example you linked also uses nats.ws, not stan.js

**Comment by bahmanbs** [comment]
@Jarema sure, we are using the same package of "nats.ws" as you said. it does not work on react native. it needs following polyfills to work, so it makes developers confused.
`
import 'react-native-url-polyfill/auto';
import 'text-encoding-polyfill';
import '@azure/core-asynciterator-polyfill'
`

**Comment by aricart** [comment]
@bahmanbs we don't have a "native" react native transport. However if you follow the last comment on https://github.com/nats-io/nats.ws/issues/195 you should be able to get started with it
