### ISSUE TITLE
Property 'on' does not exist on type 'Stan'

### ISSUE THREAD

**Issue by peZhmanParsaee** [nats-io/stan.js#206]
Hi there 

I want to use 'node-nats-streaming' npm package in Node.js, but it seems there is a problem in using 'on' method of type 'Stan'.
TypeScript reported that _Property 'on' does not exist on type 'Stan'_. 
`
import nats from "node-nats-streaming";

const stan = nats.connect('ticketing', 'abc', {
    url: 'http://localhost:4222'
});

stan.on('connect', () => {

});
`

The installed version of 'node-nats-streaming' package is 0.3.2

**Comment by aricart** [comment]
Several issues here.  You need to use require with Stan, and also I don't think the NATS library is exported by STAN.


Note if you are starting a new project you should be using JetStream and the current nats library. JetStream replaces STAN.
