### ISSUE TITLE
Breaking Changes from google-protobuff 3.21.1

### ISSUE THREAD

**Issue by tacyarg** [nats-io/stan.js#208]
Installed alongside google-protobuff v3.21.1 results in failure to process messages.

![image](https://user-images.githubusercontent.com/9097670/194679043-b9671be2-ae2a-4742-9173-651271775c3b.png)
![image](https://user-images.githubusercontent.com/9097670/194679056-f35790fc-ca19-4527-8406-c4ab5185a3a2.png)

Steps to reproduce:
* install google-protobuff version 3.21.1

Rolling back to **3.21.0** fixes the issue.

**Comment by aricart** [comment]
Not much I can do here - clearly, the micro version did something.
Also note that this library is deprecated in favor of JetStream, which is supported directly by the nats library.
See https://github.com/nats-io/nats.js

**Comment by aricart** [comment]
@tacyarg I tried with both 3.21.0 and 3.21.1, and it worked for me
