### ISSUE TITLE
Method to check delivery count

### ISSUE THREAD

**Issue by vmittal26** [nats-io/stan.js#214]
Hi , 

I am looking for method in API to get delivery count , so that based on that we can close the message or remove message from queue
however seems like is missing in documentation or in library?  could someone please help

**Comment by aricart** [comment]
I don't believe there's a delivery count in stan - note this product is end-of-life. JetStream, however does support such features. I know that the stan server had APIs for managing the server, however the stan client doesn't provide such functionality.
