### ISSUE TITLE
Nats issue is not acknowledged.Getting infinity event with same sequence id 

### ISSUE THREAD

**Issue by AfhaamANJ** [nats-io/stan.js#216]
<img width="1105" alt="image" src="https://github.com/nats-io/stan.js/assets/98511494/f29730b2-d496-4170-bdf2-0d7b7c0a8a38"/>

This was working fine for 2 months.

**Comment by aricart** [comment]
@AfhaamANJ 🤷 - this is an end-of-life product, please upgrade to JetStream.

**Comment by AfhaamANJ** [comment]
A whole application in production is running and relying on this NATS
