### ISSUE TITLE
NATS request claims

### ISSUE THREAD

**Issue by Pratik-WS** [nats-io/stan.js#217]
Hello there, I am  trying to integrate nats auth_callout in my web app which have chat feature for that i am using nats and want to use nats auth_callout for the same. So is there any way to generate request claims automatically using NSC command or I have to generate is manually in a json format?

**Comment by Jarema** [comment]
Hey!
I think you used wrong Repository.

Stan is end of life.
I guess you meant to post in [nats.js](https://github.com/nats-io/nats.js)

**Comment by Pratik-WS** [comment]
Thanks for letting me know @Jarema

**Comment by Jarema** [comment]
closing in favor of https://github.com/nats-io/nats.deno/discussions/724
